#--------------------------------------------------
# Happy Ghast vanilla friendly plugin by DerexXD
# Report all ur troubles at the link below!"
# coming soon"
#--------------------------------------------------

# Speed used for the Happy Ghast (set as attribute:flying_speed base in vanilla mob stats)
base-speed: 0.17

# If the plugin should make untamed Happy Ghasts faster too
affect-untamed-happy-ghasts: false